### ISSUE TITLE
Release ggplot2 3.2.0

### ISSUE THREAD

**Issue by thomasp85** [tidyverse/ggplot2#3285]
Prepare for release: 
 
* [x] `devtools::check()` 
* [x] `devtools::check_win_devel()` 
* [x] `rhub::check_for_cran()` 
* [x] `revdepcheck::revdep_check(num_workers = 4)` 
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release) 
* [x] Polish pkgdown reference index 
* [x] Draft blog post 
 
Submit to CRAN: 
 
* [x] `usethis::use_version('minor')` 
* [x] Update `cran-comments.md` 
* [x] `devtools::submit_cran()` 
* [x] Approve email 
 
Wait for CRAN... 
 
* [x] Accepted :tada: 
* [x] `usethis::use_github_release()` 
* [x] `usethis::use_dev_version()` 
* [x] Finish blog post 
* [x] Tweet 
* [ ] Add link to blog post in pkgdown news menu

**Comment by thomasp85** [comment]
@clauswilke, @yutannihilation, @karawoo, @dpseidel, and @hadley - Thanks for the work on finishing the release. We got all milestone issues merged just in time. We'll have a feature freeze for now so please don't merge any PR's in until 3.2.0 is released.

We'll start revdepcheck and I'll get back to you if help is needed here. @paleolimbot is interning with RStudio right now so I'll probably try to handle most of the issues together with him

**Comment by clauswilke** [comment]
Updated revdeps results are currently in #3303, in case anybody is looking for them.

**Comment by hadley** [comment]
When is ggplot2 scheduled to be released?

**Comment by clauswilke** [comment]
I don't think anybody has made a concrete schedule yet.

We still need to do a little more triaging of the revdeps. Let's say that is completed by Monday, May 13. Then we need to give maintainers of affected packages at least 2 additional weeks to fix things. So how about Monday, May 27?

**Comment by clauswilke** [comment]
I wanted to summarize the current status of where we are with the revdep check. We may need to delay our schedule until @thomasp85 is fully back.

* [ ] #3304 Improved release notes. I can prepare a PR later today.
* [ ] #3312 `pathGrob()` failure. @thomasp85 wanted to look into this.
* [ ] #3313 `facet_wrap()` and `facet_grid()` with a date variable is broken. We don't have a good course of action for this one yet.
* [ ] #3314, #3317 Issues with zero-length data. I have a PR (#3320). It would be good to get @thomasp85's review, since this touches his code.
* [ ] #3315 Differences between plyr functions and their ggplot2 replacements. It would be good if @thomasp85 could take a closer look.

**Comment by thomasp85** [comment]
I hope to be able to begin a very limited amount of work sometime next week, but experience have thought me that I’m always overly optimistic (I kept saying next week for 3 month last time — this is not as bad though)

**Comment by smouksassi** [comment]
Get well soon thomasp85 number one recommendation is to reduce screen time and stop work. We want you back soon take the time for full recovery.  I have dealt with several colleagues and family who had  concussion. It might be wiser for the team to push back the release. ( have seen many cases where concussion recovery was not understood and underestimated especially by the patient).

 https://www.healthline.com/health/concussion-recovery#recovery-tips 

(I am concerned as a health care professional pharmacist) I hope you will not even read this reply thomasp58 feel free to delete this comment.

**Comment by thomasp85** [comment]
I've got a blog post draft at https://github.com/tidyverse/tidyverse.org/pull/289 - can people give it a rundown and see if I've missed something important..?

**Comment by thomasp85** [comment]
All further release development is now happening on the `v3.2.0-rc` branch so please make sure to merge things that should be part of 3.2.0 into that branch instead of `master`. This also means that master is again open for merging of code that will not be part of 3.2.0

**Comment by thomasp85** [comment]
We will release in a week (Monday next week). All revdeps have been fixed (except for those we've decided not to), but one package hadn't been contacted about breaking changes so we'll give them a week to fix before releasing

**Comment by paleolimbot** [comment]
Just contacted the last developer!

**Comment by paleolimbot** [comment]
FYI, the last developer just released a new version of his package to CRAN and he's fixed the boxplot that was previously failing.

**Comment by thomasp85** [comment]
ggplot2 3.2.0 just submitted 🤞

**Comment by clauswilke** [comment]
Thanks for all your effort on this!

**Comment by thomasp85** [comment]
Haha — this has been 90% @paleolimbot and you, due to my strategically well-scheduled concussion. Thanks to both of you
