### ISSUE TITLE
Upkeep for ggplot2 (2024)

### ISSUE THREAD

**Issue by teunbrand** [tidyverse/ggplot2#6155]
### To begin

* [x] `pr_init("upkeep-2024-10")`

### Pre-history

* [ ] `usethis::use_readme_rmd()`
* [x] `usethis::use_roxygen_md()`
* [x] `usethis::use_github_links()`
* [ ] `usethis::use_pkgdown_github_pages()`
* [x] `usethis::use_tidy_github_labels()`
* [ ] `usethis::use_tidy_style()`
* [x] `urlchecker::url_check()`

### 2020

* [x] `usethis::use_package_doc()`
* [x] `usethis::use_testthat(3)`
* [x] Align the names of `R/` files and `test/` files

### 2021

* [x] Remove check environments section from `cran-comments.md`
* [x] Use lifecycle instead of artisanal deprecation messages

### 2022

* [x] Handle and close any still-open `master` --> `main` issues
* [x] `usethis:::use_codecov_badge("tidyverse/ggplot2")`
* [x] Update pkgdown site using instructions at <https://tidytemplate.tidyverse.org>
* [x] Update lifecycle badges with more accessible SVGs: `usethis::use_lifecycle()`

### 2023

* [x] Update copyright holder in DESCRIPTION: `person("Posit Software, PBC", role = c("cph", "fnd"))`
* [x] Run `devtools::document()` to re-generate package-level help topic with DESCRIPTION changes
* [x] `usethis::use_tidy_logo(); pkgdown::build_favicons(overwrite = TRUE)`
* [x] `usethis::use_tidy_coc()`
* [ ] Modernize citation files; see updated `use_citation()`
* [x] Use `pak::pak("tidyverse/ggplot2")` in README
* [ ] Consider running `usethis::use_tidy_dependencies()` and/or replace compat files with `use_standalone()`
* [x] Use cli errors or [file an issue](new) if you don't have time to do it now
* [x] `usethis::use_standalone("r-lib/rlang", "types-check")` instead of home grown argument checkers;
or [file an issue](new) if you don't have time to do it now
* [x] Add alt-text to pictures, plots, etc; see https://posit.co/blog/knitr-fig-alt/ for examples

### 2024

* [x] Review pkgdown output to find missing alt-text
* [x] Switch to new quarto chunk style: https://github.com/r-lib/usethis/issues/1913
* [x] Switch to `expect_snapshot(error = TRUE)` for class-less `expect_error()`: https://github.com/r-lib/usethis/issues/1918
* [x] Record upkeep date (https://github.com/r-lib/usethis/issues/1916)

### To finish

* [x] `usethis::use_mit_license()`
* [x] `usethis::use_package("R", "Depends", "4.0")`
* [x] `usethis::use_tidy_description()`
* [x] `usethis::use_tidy_github_actions()`
* [x] `devtools::build_readme()`
* [x] [Re-publish released site](https://pkgdown.r-lib.org/dev/articles/how-to-update-released-site.html) if needed

<sup>Created on 2024-10-24 with `usethis::use_tidy_upkeep_issue()`, using [usethis v3.0.0.9000](https://usethis.r-lib.org)</sup>

**Comment by teunbrand** [comment]
Why I didn't tick some bullets:

* `usethis::use_readme_rmd()`
    * This just initialised an empty readme, which is worse than the current readme
* `usethis::use_pkgdown_github_pages()`
    * Current setup seems to work fine
* `usethis::use_tidy_style()`
    * Loses some alignments around `<-` or `=` operators.
* Modernize citation files; see updated use_citation()
    * This just initialises an empty citation file, which is worse than the current one. Besides, I don't know what there is to be modernised.
* Consider running usethis::use_tidy_dependencies() and/or replace compat files with use_standalone()
    * I think we have the dependencies/compat files we need, no need to import spurious ones.
