### ISSUE TITLE
Upcoming scales 1.4.0 release

### ISSUE THREAD

**Issue by teunbrand** [tidyverse/ggplot2#6172]
The upcoming release of scales (https://github.com/r-lib/scales/issues/474) prompts a few tasks on ggplot2's side.

- [x] Prepare for future incorporation of `breaks_exp()` into `transform_exp()` (#6171)
- [ ] Remove shims like the following https://github.com/tidyverse/ggplot2/blob/b29b83151a8415093cadc8aead5024452ed7eae6/R/utilities.R#L792-L808
- [ ] Tweak `col_mix()` calls to continue to produce the same hex codes, because the shim has a `grDevices::rgb()` backend while `scales::col_mix()` is based on {farver}, producing tiny differences.
- [x] Rework default colour/fill scales to accept new palette specifications (#6112, #6216)
- [x] Ensure that default palettes can be retrieved from the theme (#5946)

**Comment by yutannihilation** [comment]
I found the dev version of scales breaks most of the visual tests by a subtle difference of `fill` (w/ CRAN version: `#4D4D4D`, w/ dev version: `#4E4E4E`). Is this expected? Do you observe this on your local? (I just tested on my Windows, so this might be platform-specific problem).

``` diff
diff --git a/tests/testthat/_snaps/aes/alpha-set-in-alpha.svg b/tests/testthat/_snaps/aes/alpha-set-in-alpha.svg
index 218cedbd2..1e08edd47 100644
--- a/tests/testthat/_snaps/aes/alpha-set-in-alpha.svg
+++ b/tests/testthat/_snaps/aes/alpha-set-in-alpha.svg
@@ -31,11 +31,11 @@
 <rect x='45.03' y='22.78' width='669.49' height='522.33' style='stroke-width: 1.07; stroke: #333333;' />
 </g>
 <g clip-path='url(#cpMC4wMHw3MjAuMDB8MC4wMHw1NzYuMDA=)'>
-<text x='40.10' y='548.14' text-anchor='end' style='font-size: 8.80px; fill: #4D4D4D; font-family: sans;' textLength='22.02px' lengthAdjust='spacingAndGlyphs'>0.950</text>
-<text x='40.10' y='417.56' text-anchor='end' style='font-size: 8.80px; fill: #4D4D4D; font-family: sans;' textLength='22.02px' lengthAdjust='spacingAndGlyphs'>0.975</text>
-<text x='40.10' y='286.98' text-anchor='end' style='font-size: 8.80px; fill: #4D4D4D; font-family: sans;' textLength='22.02px' lengthAdjust='spacingAndGlyphs'>1.000</text>
-<text x='40.10' y='156.39' text-anchor='end' style='font-size: 8.80px; fill: #4D4D4D; font-family: sans;' textLength='22.02px' lengthAdjust='spacingAndGlyphs'>1.025</text>
-<text x='40.10' y='25.81' text-anchor='end' style='font-size: 8.80px; fill: #4D4D4D; font-family: sans;' textLength='22.02px' lengthAdjust='spacingAndGlyphs'>1.050</text>
+<text x='40.10' y='548.14' text-anchor='end' style='font-size: 8.80px; fill: #4E4E4E; font-family: sans;' textLength='22.02px' lengthAdjust='spacingAndGlyphs'>0.950</text>
+<text x='40.10' y='417.56' text-anchor='end' style='font-size: 8.80px; fill: #4E4E4E; font-family: sans;' textLength='22.02px' lengthAdjust='spacingAndGlyphs'>0.975</text>
+<text x='40.10' y='286.98' text-anchor='end' style='font-size: 8.80px; fill: #4E4E4E; font-family: sans;' textLength='22.02px' lengthAdjust='spacingAndGlyphs'>1.000</text>
+<text x='40.10' y='156.39' text-anchor='end' style='font-size: 8.80px; fill: #4E4E4E; font-family: sans;' textLength='22.02px' lengthAdjust='spacingAndGlyphs'>1.025</text>
+<text x='40.10' y='25.81' text-anchor='end' style='font-size: 8.80px; fill: #4E4E4E; font-family: sans;' textLength='22.02px' lengthAdjust='spacingAndGlyphs'>1.050</text>
 <polyline points='42.29,545.11 45.03,545.11 ' style='stroke-width: 1.07; stroke: #333333; stroke-linecap: butt;' />
 <polyline points='42.29,414.53 45.03,414.53 ' style='stroke-width: 1.07; stroke: #333333; stroke-linecap: butt;' />
 <polyline points='42.29,283.95 45.03,283.95 ' style='stroke-width: 1.07; stroke: #333333; stroke-linecap: butt;' />
```

**Comment by yutannihilation** [comment]
Ah, thanks for the details! I didn't notice that bullet is about this and there's a plan. Great.
